### ISSUE TITLE
Unknown function: StripTrailingWhitespaces

### ISSUE THREAD

**Issue by vlazzle** [vicalejuri/startervim#10]
When I'm editing a *.js or *.rb or *.py file and then do :w or :x, I get the following error:

Error detected while processing BufWrite Auto commands for "*.rb":  
E117: Unknown function: StripTrailingWhitespaces

This only happens for certain filetypes. For example, it doesn't happen with *.c files.

**Comment by thedjpetersen** [comment]
Adding this function should fix it:

``` vim
function! <SID>StripTrailingWhitespaces()
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " Do the business:
    %s/\s\+$//e
    " Clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction
```

http://vimcasts.org/episodes/tidying-whitespace/

**Comment by vlazzle** [comment]
Thanks!

Actually, I can only get it to work by taking out the &lt;SID&gt; part before the function name. Do you think this will cause any problems in the future?

**Comment by thedjpetersen** [comment]
you should leave the <SID> part of the function in, and farther down reference the function like this:

```
s:StripTrailingWhitespaces()
```

**Comment by vlazzle** [comment]
but i'm not the one who references the function. it's called by autocmd when i save a file (i didn't set this up, and grepping for s:StripTrailingWhitespaces in the .vim directory yields no results, somehow...)

**Comment by vicalejuri** [comment]
I've forgot to include StripTrailingWhitespaces function. I've released a new version that should have this fixed.

Meanwhile, you can fix that issue changing `StripTrailingWhitespaces` on the file `.vimrc` to `s:StripTrailingWhitespaces` as mentioned by thedjpetersen.

**Comment by vlazzle** [comment]
Thanks! I installed the latest version and it corrected this issue.

I also just sent you a pull request for something else.
