### ISSUE TITLE
Vundle instead of Bundles

### ISSUE THREAD

**Issue by andrusha** [vicalejuri/startervim#11]
I found that Vundle (https://github.com/gmarik/vundle) is more convenient  way to manage bundles.
First of all it uses pure-vim syntax, you don't put your bundles in comments, it also allows you to search for plugins and update them easily.

**Comment by vicalejuri** [comment]
I'm working on that. When i created starter vim, the whole pathogen/bundle scene was quite new in vim. Thanks!

**Comment by vicalejuri** [comment]
I've just commited a new version that uses Vundle. Check it out!

Don't forget to issue a `:BundleInstall` on the first time you've opened your vim.
