### ISSUE TITLE
Redundant "bundles".

### ISSUE THREAD

**Issue by romainl** [vicalejuri/startervim#7]
I, thanks for your work but I'm wondering: Why do you have both Align and Tabular? 

Both plugins are made to align text vertically so having both looks like bloat to me.

Also Matchit is already provided by Vim. You enable it with `runtime macros/matchit.vim`.

Thanks again.

**Comment by vicalejuri** [comment]
Thanks for the tip `matchit` tip! 

I've removed `Align` from the new version, and only include `Tabular` for now.
